
--Elimina registros duplicados en una tabla segun criterio de busqueda

DECLARE @PLL TABLE 
(
	ID_PARTICION INT,
	ID INT,
	ID_RESOLUCION int,
	ID_TIPO_HOMOLOGA int,
	ID_HOMOLOGA int
	,ID_PLANTILLA int
)

INSERT INTO @PLL	
SELECT ROW_NUMBER() over (partition by ID_RESOLUCION, ID_TIPO_HOMOLOGA, ID_HOMOLOGA, ID_PLANTILLA ORDER BY ID DESC ) ID_PARTICION
	,TP_HOMOLOGA_RES4505.ID
	,TP_HOMOLOGA_RES4505.ID_RESOLUCION
	,TP_HOMOLOGA_RES4505.ID_TIPO_HOMOLOGA
	,TP_HOMOLOGA_RES4505.ID_HOMOLOGA
	,TP_HOMOLOGA_RES4505.ID_PLANTILLA					
FROM	
	parametrizacion.tp_homologa_res4505

DELETE Parametrizacion.TP_HOMOLOGA_DATOS_RES4505
FROM @PLL
INNER JOIN Parametrizacion.TP_HOMOLOGA_DATOS_RES4505
ON [@PLL].ID_PARTICION > 1
AND TP_HOMOLOGA_DATOS_RES4505.ID_HOMOLOGA_RES4505 = [@PLL].ID

DELETE parametrizacion.tp_homologa_res4505
FROM @PLL
INNER JOIN Parametrizacion.tp_homologa_res4505
ON [@PLL].ID_PARTICION > 1
AND tp_homologa_res4505.ID = [@PLL].ID
